<?php defined( 'ABSPATH' ) || exit; ?>
<div class="wrap olr-pp-admin">
	<h1>Phone Popup</h1>
	<?php if ( $notice ) : ?><div class="notice <?php echo $notice['error'] ? 'notice-error' : 'notice-success'; ?> is-dismissible"><p><?php echo esc_html( $notice['text'] ); ?></p></div><?php endif; ?>
	<div class="olr-pp-admin__intro"><div><p class="olr-pp-admin__eyebrow">OFF LABEL / MEMBER DETAILS</p><h2>A number. A connection.</h2><p>Collect mobile numbers from your members, right where you want to ask.</p></div><span class="olr-pp-admin__status"><?php echo OLR_Phone_Popup::configured() ? 'Popup enabled' : 'Popup off'; ?></span></div>
	<form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" id="olr-pp-settings">
		<input type="hidden" name="action" value="olr_pp_settings"><?php wp_nonce_field( 'olr_pp_settings' ); ?>
		<div class="olr-pp-admin__layout"><div class="olr-pp-admin__main">
			<section class="olr-pp-admin__card" aria-labelledby="pp-placement"><h2 id="pp-placement"><span>01</span> Where it appears</h2>
				<label class="olr-pp-admin__check"><input type="checkbox" name="settings[enabled]" value="1" <?php checked( $s['enabled'], 1 ); ?>> Enable the popup</label>
				<p class="description">Only signed-in members see it, so every number saves to the correct account. New members can see it on their first page after signing in.</p>
				<label class="olr-pp-admin__check"><input type="checkbox" id="pp-all-pages" name="settings[all_pages]" value="1" <?php checked( $s['all_pages'], 1 ); ?>> Show on all published pages</label>
				<div id="pp-page-picker"><label class="olr-pp-admin__label" for="pp-page-search">Choose pages</label><input type="search" id="pp-page-search" placeholder="Search pages…" autocomplete="off" aria-controls="pp-pages">
				<div class="olr-pp-admin__pages" id="pp-pages">
				<?php foreach ( $pages as $page ) : ?><label class="olr-pp-admin__page"><input type="checkbox" name="settings[pages][]" value="<?php echo esc_attr( $page->ID ); ?>" <?php checked( in_array( (int) $page->ID, array_map( 'intval', $s['pages'] ), true ) ); ?>><span><?php echo esc_html( $page->post_title ?: '(Untitled)' ); ?></span><small>#<?php echo esc_html( $page->ID ); ?></small></label><?php endforeach; ?>
				<?php if ( ! $pages ) : ?><p>Create and publish a WordPress page first.</p><?php endif; ?>
				</div><p id="pp-page-count" class="description" aria-live="polite"></p></div>
				<label class="olr-pp-admin__label" for="pp-audience">Who sees it</label><select id="pp-audience" name="settings[audience]"><option value="missing" <?php selected( $s['audience'], 'missing' ); ?>>Members with no billing phone number</option><option value="all" <?php selected( $s['audience'], 'all' ); ?>>Members who have not opted in through this popup</option></select>
				<p class="description">The second option requires SMS signup and can prefill an existing number. Past popup opt-ins are not prompted again. Existing Omnisend subscribers do not receive another first-subscription coupon.</p>
				<div class="olr-pp-admin__pair"><div><label class="olr-pp-admin__label" for="pp-delay">Show after (seconds)</label><input type="number" id="pp-delay" name="settings[delay]" min="0" max="60" value="<?php echo esc_attr( $s['delay'] ); ?>"></div><div><label class="olr-pp-admin__label" for="pp-cooldown">Ask again after dismissal (days)</label><input type="number" id="pp-cooldown" name="settings[cooldown]" min="1" max="365" value="<?php echo esc_attr( $s['cooldown'] ); ?>"></div></div>
			</section>
			<section class="olr-pp-admin__card" aria-labelledby="pp-copy"><h2 id="pp-copy"><span>02</span> What it says</h2>
				<label class="olr-pp-admin__label" for="pp-title">Heading</label><input type="text" id="pp-title" name="settings[title]" maxlength="100" value="<?php echo esc_attr( $s['title'] ); ?>">
				<label class="olr-pp-admin__label" for="pp-body">Message</label><textarea id="pp-body" name="settings[body]" rows="3" maxlength="500"><?php echo esc_textarea( $s['body'] ); ?></textarea>
				<label class="olr-pp-admin__label" for="pp-button">Button text</label><input type="text" id="pp-button" name="settings[button]" maxlength="60" value="<?php echo esc_attr( $s['button'] ); ?>">
				<label class="olr-pp-admin__check"><input type="checkbox" id="pp-local" name="settings[local_numbers]" value="1" <?php checked( $s['local_numbers'], 1 ); ?>> Accept US / Canada numbers without a country code</label><p class="description">These numbers are saved with +1. Other countries must include their country code.</p>
			</section>
			<section class="olr-pp-admin__card" aria-labelledby="pp-sms"><h2 id="pp-sms"><span>03</span> Text signup &amp; Omnisend</h2>
				<label class="olr-pp-admin__check"><input type="checkbox" id="pp-enable-sms" name="settings[sms]" value="1" <?php checked( $s['sms'], 1 ); ?>> Collect SMS consent and send opt-ins to Omnisend</label><p class="description">When off, this plugin only saves the account phone number. When on, members must check the SMS consent box to submit this offer.</p>
				<label class="olr-pp-admin__label" for="pp-key">Omnisend API key</label><input type="password" id="pp-key" name="api_key" autocomplete="new-password" value="" placeholder="<?php echo OLR_PP_Omnisend::key() ? 'A key is saved. Leave blank to keep it.' : 'Paste a key with contacts.read and contacts.write'; ?>" <?php disabled( defined( 'OLR_PHONE_POPUP_OMNISEND_KEY' ) ); ?>>
				<?php if ( defined( 'OLR_PHONE_POPUP_OMNISEND_KEY' ) ) : ?><p class="description">The key is configured in wp-config.php.</p><?php elseif ( OLR_PP_Omnisend::key() ) : ?><label class="olr-pp-admin__check"><input type="checkbox" name="remove_key" value="1"> Remove the saved API key</label><?php endif; ?>
				<label class="olr-pp-admin__label" for="pp-consent">SMS consent wording</label><textarea id="pp-consent" name="settings[consent]" rows="5" maxlength="1500"><?php echo esc_textarea( $s['consent'] ); ?></textarea><p class="description">Use your approved SMS disclosure. Keep your brand name, recurring marketing consent, message rates and frequency, STOP / HELP instructions, and no-purchase-condition wording.</p>
				<label class="olr-pp-admin__label" for="pp-terms">SMS terms URL</label><input type="url" id="pp-terms" name="settings[terms_url]" placeholder="https://…" value="<?php echo esc_attr( $s['terms_url'] ); ?>">
				<label class="olr-pp-admin__label" for="pp-privacy">Privacy policy URL</label><input type="url" id="pp-privacy" name="settings[privacy_url]" placeholder="https://…" value="<?php echo esc_attr( $s['privacy_url'] ); ?>">
				<div class="olr-pp-admin__note"><strong>Set up the coupon text in Omnisend</strong><ol><li>Create a Welcome automation with <b>Subscribed to Marketing</b> as its trigger.</li><li>Filter to <b>SMS</b>, <b>First subscription = true</b>, and <b>Origin = API</b>. Remove the default “Signup form” method filter.</li><li>Add an SMS with your unique WooCommerce discount code. Enable WooCommerce discount generation first.</li><li>Remove intentional delays, then enable the workflow before enabling this popup. Quiet hours and carrier delivery still apply.</li></ol><p>Use offer copy that matches the coupon you configure. This plugin saves and subscribes the contact; Omnisend creates the code and sends the text.</p><a href="https://support.omnisend.com/en/articles/9470439-add-unique-discounts-to-automated-sms-mms" target="_blank" rel="noopener noreferrer">Omnisend coupon setup ↗</a></div>
			</section>
			<div class="olr-pp-admin__save"><?php submit_button( 'Save settings', 'primary', 'submit', false ); ?><button type="button" class="button" data-pp-preview>Preview popup</button></div>
		</div><aside class="olr-pp-admin__aside">
			<section class="olr-pp-admin__card"><p class="olr-pp-admin__eyebrow">ONE ACCOUNT FIELD</p><h2>Saved where it belongs.</h2><p>Every submission updates the member’s existing WooCommerce billing phone.</p><code>billing_phone</code><p class="description">Matches the billing_phone column in your export. No new phone field is created. Shipping phone numbers are not changed.</p></section>
			<section class="olr-pp-admin__card"><h2>See it before it’s live</h2><p>Preview your current wording and consent form. Nothing is saved or sent in the preview.</p><button type="button" class="button" data-pp-preview>Preview popup</button></section>
			<section class="olr-pp-admin__card"><h2>After signup</h2><p>The popup stops appearing. Dismissals are remembered on the member’s account across devices.</p><p class="description">Use a page members reach after login, such as Account or Shop. Logged-out visitors and pending accounts that cannot sign in will not see it.</p></section>
		</aside></div>
	</form>
	<section class="olr-pp-admin__card olr-pp-admin__activity"><div class="olr-pp-admin__activity-heading"><h2>Captured accounts</h2><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><input type="hidden" name="action" value="olr_pp_connection"><?php wp_nonce_field( 'olr_pp_connection' ); ?><button class="button" type="submit" <?php disabled( ! OLR_PP_Omnisend::key() ); ?>>Test saved Omnisend connection</button></form></div><p class="description">Most recent submissions first. “Synced” confirms the subscription, not delivery of a text. Omnisend remains the source for current subscription status and delivery reports.</p>
		<div class="olr-pp-admin__table"><table class="widefat striped"><thead><tr><th scope="col">Member</th><th scope="col">Account phone</th><th scope="col">Saved (UTC)</th><th scope="col">Signup status</th><th scope="col">Action</th></tr></thead><tbody>
		<?php foreach ( $members->get_results() as $member ) : $state = OLR_Phone_Popup::state( $member->ID ); ?>
			<tr><td><a href="<?php echo esc_url( get_edit_user_link( $member->ID ) ); ?>"><?php echo esc_html( $member->display_name ); ?></a></td><td><?php echo esc_html( get_user_meta( $member->ID, OLR_Phone_Popup::PHONE_META, true ) ); ?></td><td><?php echo esc_html( isset( $state['saved_at'] ) ? gmdate( 'Y-m-d H:i', strtotime( $state['saved_at'] ) ) : '—' ); ?></td><td><strong><?php echo esc_html( ucfirst( $state['status'] ?? 'Unknown' ) ); ?></strong><?php if ( ! empty( $state['error'] ) ) : ?><p><?php echo esc_html( $state['error'] ); ?></p><?php endif; ?></td><td>
			<?php if ( in_array( $state['status'] ?? '', array( 'failed', 'pending' ), true ) && ! in_array( $state['error_code'] ?? '', array( 'unsubscribed', 'changed', 'expired' ), true ) ) : ?><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><input type="hidden" name="action" value="olr_pp_retry"><input type="hidden" name="member" value="<?php echo esc_attr( $member->ID ); ?>"><?php wp_nonce_field( 'olr_pp_retry' ); ?><button class="button" type="submit">Retry sync</button></form><?php else : ?>—<?php endif; ?></td></tr>
		<?php endforeach; ?>
		<?php if ( ! $members->get_results() ) : ?><tr><td colspan="5">No submissions yet. Choose your pages, preview the form, then enable the popup.</td></tr><?php endif; ?>
		</tbody></table></div>
		<?php echo wp_kses_post( paginate_links( array( 'base' => add_query_arg( 'pp_page', '%#%', admin_url( 'admin.php?page=olr-phone-popup' ) ), 'format' => '', 'current' => $activity_page, 'total' => (int) ceil( $members->get_total() / 15 ) ) ) ); ?>
	</section>
</div>
<?php OLR_Phone_Popup::render_dialog( $s, true ); ?>
