<?php
/** Real WooCommerce/UAP fixture; integration.php refuses all non-test databases. */
require __DIR__ . '/integration.php';
$original_code = OLR_Affiliate_Service::coupon_code( $uid );
$original_rank = $indeed_db->get_affiliate_rank( 0, $uid );
$original_affiliate = OLR_Account_Hub::affiliate_id( $uid );
$original_referrals = $wpdb->get_var( $wpdb->prepare( "SELECT COUNT(*) FROM {$wpdb->prefix}uap_referrals WHERE affiliate_id=%d", $original_affiliate ) );
$suffix = bin2hex( random_bytes( 4 ) );
$custom = OLR_Affiliate_Coupons::choose( $uid, 'MY-CODE-' . strtoupper( $suffix ) );
verify( strtolower( $custom ) === 'my-code-' . $suffix && $custom === OLR_Affiliate_Service::coupon_code( $uid ), 'member can select an available code as their primary code' );
verify( $custom === OLR_Affiliate_Coupons::choose( $uid, strtoupper( $custom ) ), 'case-insensitive retry reuses the existing own code' );
verify( wc_get_coupon_id_by_code( $original_code ) && $indeed_db->get_affiliate_for_coupon_code( strtolower( $original_code ) ) == $original_affiliate, 'old code remains usable and attributed to the original affiliate' );
verify( $original_affiliate === OLR_Account_Hub::affiliate_id( $uid ) && $original_rank == $indeed_db->get_affiliate_rank( 0, $uid ) && $original_referrals == $wpdb->get_var( $wpdb->prepare( "SELECT COUNT(*) FROM {$wpdb->prefix}uap_referrals WHERE affiliate_id=%d", $original_affiliate ) ), 'choosing a code preserves affiliate ID, rank and referral history' );
$other_uid = member(); OLR_Affiliate_Service::activate( $other_uid, true );
refuses( function () use ( $other_uid, $custom ) { OLR_Affiliate_Coupons::choose( $other_uid, strtoupper( $custom ) ); }, 'another affiliate cannot take the code using different capitalization' );
$promo = new WC_Coupon(); $promo->set_code( 'brand-' . $suffix ); $promo->set_discount_type( 'percent' ); $promo->set_amount( 40 ); $promo->save();
refuses( function () use ( $uid, $promo ) { OLR_Affiliate_Coupons::choose( $uid, strtoupper( $promo->get_code() ) ); }, 'existing WooCommerce promotion cannot be claimed' );
wp_update_post( array( 'ID' => $promo->get_id(), 'post_status' => 'draft' ) );
refuses( function () use ( $uid, $promo ) { OLR_Affiliate_Coupons::choose( $uid, $promo->get_code() ); }, 'draft WooCommerce coupon name remains unavailable' );
wp_trash_post( $promo->get_id() );
refuses( function () use ( $uid, $promo ) { OLR_Affiliate_Coupons::choose( $uid, $promo->get_code() ); }, 'trashed WooCommerce coupon name remains unavailable' );
foreach ( array( '', 'xy', 'space code', '<script>', str_repeat( 'a', 33 ) ) as $bad ) { refuses( function () use ( $uid, $bad ) { OLR_Affiliate_Coupons::choose( $uid, $bad ); }, 'invalid code format refused: ' . $bad ); }
OLR_Affiliate_Service::set_block( $other_uid, true );
refuses( function () use ( $other_uid ) { OLR_Affiliate_Coupons::choose( $other_uid, 'blocked-new-code' ); }, 'suspended affiliate cannot choose a code' );
OLR_Affiliate_Service::set_block( $other_uid, false );
wp_set_current_user( $uid );
refuses( function () { OLR_Affiliate_Coupons::save_default( 50 ); }, 'member cannot change the default customer discount' );
refuses( function () use ( $uid ) { OLR_Affiliate_Coupons::save_override( $uid, 50 ); }, 'member cannot change their own customer discount' );
wp_set_current_user( $admin->ID );
foreach ( array( '-1', '0', '101', '25.555', 'NaN' ) as $bad ) { refuses( function () use ( $bad ) { OLR_Affiliate_Coupons::save_default( $bad ); }, 'invalid discount refused: ' . $bad ); }
OLR_Affiliate_Coupons::save_default( '25' );
verify( (float) ( new WC_Coupon( $custom ) )->get_amount() === 25.0 && (float) ( new WC_Coupon( $original_code ) )->get_amount() === 25.0, 'global default updates existing managed primary and previous codes' );
verify( (float) ( new WC_Coupon( $promo->get_id() ) )->get_amount() === 40.0, 'global default leaves unrelated WooCommerce promotion unchanged' );
OLR_Affiliate_Coupons::save_override( $uid, '17.50' );
OLR_Affiliate_Coupons::save_default( '30' );
verify( (float) ( new WC_Coupon( $custom ) )->get_amount() === 17.5 && (float) ( new WC_Coupon( $original_code ) )->get_amount() === 17.5, 'individual override applies to all member codes and survives default changes' );
verify( (float) ( new WC_Coupon( OLR_Affiliate_Service::coupon_code( $other_uid ) ) )->get_amount() === 30.0, 'affiliate without override follows updated default' );
verify( OLR_Affiliate_Coupons::offer( $uid ) === '17.5%' && OLR_Account_Hub::affiliate_program_policy()['customer_discount'] === '30%', 'member and public offer copy reflect actual individual and default discounts' );
$guidelines = OLR_Account_Hub::instance()->affiliate_guidelines_shortcode();
verify( strpos( $guidelines, '$60.00' ) !== false && strpos( $guidelines, '$140.00' ) !== false && strpos( $guidelines, '$14.00' ) !== false, 'public earnings example recalculates for the configured customer discount' );
$_GET['member_search'] = get_userdata( $uid )->user_email;
ob_start(); OLR_Affiliate_Flows::admin_page(); $admin_html = ob_get_clean();
unset( $_GET['member_search'] );
verify( strpos( $admin_html, 'Default customer discount (%)' ) !== false && strpos( $admin_html, 'Individual customer discount (%)' ) !== false && strpos( $admin_html, 'coupon_override' ) !== false, 'administrator sees both default and per-member discount forms' );
wp_set_current_user( $uid );
$second = OLR_Affiliate_Coupons::choose( $uid, 'second-' . $suffix );
verify( (float) ( new WC_Coupon( $second ) )->get_amount() === 17.5, 'new custom code inherits the member discount' );
verify( $indeed_db->get_coupon_data( $second )['amount_type'] === $indeed_db->get_coupon_data( $custom )['amount_type'], 'coupon commission configuration is preserved independently of customer discount' );
$new_buyer = member(); WC()->customer = new WC_Customer( $new_buyer ); WC()->customer->set_billing_email( get_userdata( $new_buyer )->user_email );
WC()->cart->empty_cart(); WC()->session->set( 'olr_credit_use', false ); WC()->cart->add_to_cart( $product->get_id() );
verify( WC()->cart->apply_coupon( $second ), 'new customer can apply the chosen custom code' );
WC()->cart->calculate_totals();
verify( abs( (float) WC()->cart->get_discount_total() - 17.5 ) < .001, 'real checkout calculates configured 17.5 percent customer discount' );
$custom_order = WC()->checkout()->create_order( array( 'billing_email' => get_userdata( $new_buyer )->user_email, 'payment_method' => 'bacs' ) );
verify( ! is_wp_error( $custom_order ) && $wpdb->get_var( $wpdb->prepare( "SELECT id FROM {$wpdb->prefix}uap_referrals WHERE affiliate_id=%d AND reference=%s", $original_affiliate, (string) $custom_order ) ), 'chosen code order is attributed through real UAP integration' );
wp_set_current_user( $admin->ID ); OLR_Affiliate_Coupons::save_override( $uid, '' );
verify( (float) ( new WC_Coupon( $second ) )->get_amount() === 30.0, 'clearing individual override restores the current default' );
$fail_id = wc_get_coupon_id_by_code( $custom );
$fail_save = static function ( $coupon ) use ( $fail_id ) { if ( $coupon instanceof WC_Coupon && $coupon->get_id() === $fail_id && (float) $coupon->get_amount( 'edit' ) === 55.0 ) { throw new RuntimeException( 'Injected coupon save failure' ); } };
add_action( 'woocommerce_before_data_object_save', $fail_save );
refuses( function () use ( $uid ) { OLR_Affiliate_Coupons::save_override( $uid, '55' ); }, 'individual discount update rolls back after an interrupted coupon save' );
verify( '' === get_user_meta( $uid, OLR_Affiliate_Coupons::OVERRIDE_META, true ) && (float) ( new WC_Coupon( $original_code ) )->get_amount() === 30.0, 'rollback clears stale user/coupon cache and restores previous individual policy' );
refuses( function () { OLR_Affiliate_Coupons::save_default( '55' ); }, 'global update rolls back after an interrupted coupon save' );
verify( (float) OLR_Affiliate_Coupons::default_percent() === 30.0 && (float) ( new WC_Coupon( $original_code ) )->get_amount() === 30.0, 'rollback restores global option and previously updated coupons' );
remove_action( 'woocommerce_before_data_object_save', $fail_save );
OLR_Affiliate_Coupons::save_default( '20' ); // Keep the baseline fixture deterministic for other suites.
$context_path = dirname( $fixture ) . '/context.json';
$context = json_decode( file_get_contents( $context_path ), true );
$context['code_race_users'] = array( $uid, $other_uid ); $context['code_race_name'] = 'race-' . $suffix;
file_put_contents( $context_path, wp_json_encode( $context ) );
echo "Completed $checks combined integration/coupon checks.\n";
